# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rawgenai < Formula
  desc "CLI tool for AI agents to access raw AI capabilities (TTS, STT, Image, Video)"
  homepage "https://github.com/WHQ25/rawgenai"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.10.1/rawgenai_0.10.1_darwin_amd64.tar.gz"
      sha256 "cc60bb7085fe3aca434030f524268b01cbf94d1794cd7daf13000aaa92340870"

      def install
        bin.install "rawgenai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.10.1/rawgenai_0.10.1_darwin_arm64.tar.gz"
      sha256 "3a15eab57edca9c0dfae109ad841a308fece6ee8eeb71488cba01bc10a9812c8"

      def install
        bin.install "rawgenai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.10.1/rawgenai_0.10.1_linux_amd64.tar.gz"
      sha256 "c43aa2bbe7eadca922f730431c1c16e37c76e2accbe4c65fb130b6fc0a8f6ef6"
      def install
        bin.install "rawgenai"
      end
    end
  end

  test do
    system "#{bin}/rawgenai", "--version"
  end
end
