# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rawgenai < Formula
  desc "CLI tool for AI agents to access raw AI capabilities (TTS, STT, Image, Video)"
  homepage "https://github.com/WHQ25/rawgenai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.1.0/rawgenai_0.1.0_darwin_amd64.tar.gz"
      sha256 "a07417a23a4df17c0d0402ad8a28009be45fecf85a361c199e591e7ba13639a7"

      def install
        bin.install "rawgenai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.1.0/rawgenai_0.1.0_darwin_arm64.tar.gz"
      sha256 "c860949cfdda8e5b3a8bf158442461fb7e20aa7e77146b66e65bffee22529cd5"

      def install
        bin.install "rawgenai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.1.0/rawgenai_0.1.0_linux_amd64.tar.gz"
      sha256 "d438f3de48b70b91690ca9f1388ca100a1ab9df24be48e9f9158b78dac3c0769"
      def install
        bin.install "rawgenai"
      end
    end
  end

  test do
    system "#{bin}/rawgenai", "--version"
  end
end
