# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rawgenai < Formula
  desc "CLI tool for AI agents to access raw AI capabilities (TTS, STT, Image, Video)"
  homepage "https://github.com/WHQ25/rawgenai"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.5.0/rawgenai_0.5.0_darwin_amd64.tar.gz"
      sha256 "0e0029b72ddb4b7e06b8d99f914b4da90c6bed952bc4a6eb2699999e875291ee"

      def install
        bin.install "rawgenai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.5.0/rawgenai_0.5.0_darwin_arm64.tar.gz"
      sha256 "4e2da024b40ba36e52ea651a9be2b6e0fd07e89f7decaa321c25b624536914b2"

      def install
        bin.install "rawgenai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WHQ25/rawgenai/releases/download/v0.5.0/rawgenai_0.5.0_linux_amd64.tar.gz"
      sha256 "502ed58816e6e59834143d6f5df0b5050b25085d282489defd5f1b40f49041cd"
      def install
        bin.install "rawgenai"
      end
    end
  end

  test do
    system "#{bin}/rawgenai", "--version"
  end
end
